# Generated by Django 5.1.11 on 2025-09-02 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("MEMBER", "Lid (woningruil)"),
                            ("OWNER", "Huizenbezitter"),
                            ("AGENCY", "Makelaar"),
                        ],
                        default="MEMBER",
                        max_length=16,
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("is_premium", models.BooleanField(default=False)),
                ("display_name", models.CharField(blank=True, max_length=120)),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("address", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("bio", models.TextField(blank=True)),
                ("slug", models.SlugField(blank=True, max_length=150, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
