# Generated by Django 5.1.11 on 2025-09-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_profile_city_alter_profile_province_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="premium",
            field=models.BooleanField(default=False, help_text="Premium toegang"),
        ),
    ]
