# Generated by Django 5.1.11 on 2025-09-03 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_profile_city_alter_profile_premium_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgencyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_legal_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Bedrijfsnaam (juridisch)",
                    ),
                ),
                (
                    "company_trade_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Handelsnaam"
                    ),
                ),
                (
                    "kvk_number",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="KVK-nummer"
                    ),
                ),
                (
                    "vat_number",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="BTW-nummer"
                    ),
                ),
                (
                    "reg_address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Vestigingsadres"
                    ),
                ),
                (
                    "reg_postcode",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="Postcode"
                    ),
                ),
                (
                    "reg_city",
                    models.CharField(blank=True, max_length=120, verbose_name="Plaats"),
                ),
                (
                    "reg_province",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Provincie"
                    ),
                ),
                (
                    "post_address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Postadres"
                    ),
                ),
                (
                    "post_postcode",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="Postcode (post)"
                    ),
                ),
                (
                    "post_city",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Plaats (post)"
                    ),
                ),
                (
                    "post_province",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Provincie (post)"
                    ),
                ),
                (
                    "primary_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Primair e-mail"
                    ),
                ),
                (
                    "primary_phone",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Telefoon"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "hq_opening_hours",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Openingstijden (hoofdkantoor)",
                    ),
                ),
                (
                    "extra_branches",
                    models.TextField(
                        blank=True,
                        verbose_name="Extra vestigingen (één per regel: adres | tel | openingstijden)",
                    ),
                ),
                (
                    "lead_contacts",
                    models.TextField(
                        blank=True,
                        verbose_name="Contactpersonen leads (één per regel: naam | rol | e-mail | tel)",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="agency/logo/"),
                ),
                (
                    "cover",
                    models.ImageField(blank=True, null=True, upload_to="agency/cover/"),
                ),
                (
                    "brand_primary_color",
                    models.CharField(blank=True, default="#0d6efd", max_length=7),
                ),
                (
                    "brand_secondary_color",
                    models.CharField(blank=True, default="#6c757d", max_length=7),
                ),
                (
                    "brand_accent_color",
                    models.CharField(blank=True, default="#198754", max_length=7),
                ),
                (
                    "brand_style",
                    models.TextField(
                        blank=True, verbose_name="Kleuren/merkstijl (notities)"
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, verbose_name="Korte bio/omschrijving"),
                ),
                ("linkedin_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agency_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
