# Generated by Django 5.1.11 on 2025-09-02 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('my_title', models.CharField(max_length=200)),
                ('my_city', models.CharField(max_length=120)),
                ('my_property_type', models.CharField(choices=[('appartement', 'Appartement'), ('rijtjeshuis', 'Rijtjeshuis'), ('vrijstaand', 'Vrijstaand'), ('studio', 'Studio'), ('tussenwoning', 'Tussenwoning'), ('hoekwoning', 'Hoekwoning')], max_length=20)),
                ('my_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('my_description', models.TextField(blank=True)),
                ('my_living_area', models.PositiveIntegerField()),
                ('my_rooms', models.PositiveIntegerField()),
                ('my_floor', models.IntegerField(blank=True, null=True)),
                ('my_balcony', models.BooleanField(default=False)),
                ('my_terrace', models.BooleanField(default=False)),
                ('my_garden', models.BooleanField(default=False)),
                ('my_storage', models.BooleanField(default=False)),
                ('my_attic', models.BooleanField(default=False)),
                ('my_cellar', models.BooleanField(default=False)),
                ('my_parking_street', models.BooleanField(default=False)),
                ('my_parking_garage', models.BooleanField(default=False)),
                ('my_parking_private', models.BooleanField(default=False)),
                ('my_near_shops', models.BooleanField(default=False)),
                ('my_near_schools', models.BooleanField(default=False)),
                ('my_ov', models.BooleanField(default=False)),
                ('my_floorplan', models.ImageField(blank=True, null=True, upload_to='exchange_floorplans/')),
                ('want_city', models.CharField(blank=True, max_length=120)),
                ('want_property_type', models.CharField(blank=True, choices=[('appartement', 'Appartement'), ('rijtjeshuis', 'Rijtjeshuis'), ('vrijstaand', 'Vrijstaand'), ('studio', 'Studio'), ('tussenwoning', 'Tussenwoning'), ('hoekwoning', 'Hoekwoning')], max_length=20)),
                ('want_min_area', models.PositiveIntegerField(blank=True, null=True)),
                ('want_min_rooms', models.PositiveIntegerField(blank=True, null=True)),
                ('want_balcony', models.BooleanField(default=False)),
                ('want_terrace', models.BooleanField(default=False)),
                ('want_garden', models.BooleanField(default=False)),
                ('want_storage', models.BooleanField(default=False)),
                ('want_attic', models.BooleanField(default=False)),
                ('want_cellar', models.BooleanField(default=False)),
                ('want_parking_private', models.BooleanField(default=False)),
                ('want_ov', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangeOfferImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='exchange_images/')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.exchangeoffer')),
            ],
        ),
        migrations.CreateModel(
            name='MarketListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('city', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('listing_kind', models.CharField(choices=[('HUUR', 'Huur'), ('KOOP', 'Koop')], default='HUUR', max_length=8)),
                ('property_type', models.CharField(choices=[('appartement', 'Appartement'), ('rijtjeshuis', 'Rijtjeshuis'), ('vrijstaand', 'Vrijstaand'), ('studio', 'Studio'), ('tussenwoning', 'Tussenwoning'), ('hoekwoning', 'Hoekwoning')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('living_area', models.PositiveIntegerField()),
                ('rooms', models.PositiveIntegerField()),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('balcony', models.BooleanField(default=False)),
                ('terrace', models.BooleanField(default=False)),
                ('garden', models.BooleanField(default=False)),
                ('storage', models.BooleanField(default=False)),
                ('attic', models.BooleanField(default=False)),
                ('cellar', models.BooleanField(default=False)),
                ('parking_street', models.BooleanField(default=False)),
                ('parking_garage', models.BooleanField(default=False)),
                ('parking_private', models.BooleanField(default=False)),
                ('near_shops', models.BooleanField(default=False)),
                ('near_schools', models.BooleanField(default=False)),
                ('ov', models.BooleanField(default=False)),
                ('floorplan', models.ImageField(blank=True, null=True, upload_to='floorplans/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listing_images/')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.marketlisting')),
            ],
        ),
    ]
