# Generated by Django 5.1.11 on 2025-09-03 04:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_wish'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangeoffer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='marketlisting',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='exchangeoffer',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exchangeoffer',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exchangeoffer',
            name='my_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='exchangeoffer',
            name='my_living_area',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='exchangeoffer',
            name='my_property_type',
            field=models.CharField(blank=True, choices=[('appartement', 'Appartement'), ('rijtjeshuis', 'Rijtjeshuis'), ('vrijstaand', 'Vrijstaand'), ('studio', 'Studio'), ('tussenwoning', 'Tussenwoning'), ('hoekwoning', 'Hoekwoning')], max_length=20),
        ),
        migrations.AlterField(
            model_name='exchangeoffer',
            name='my_rooms',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='exchangeoffer',
            name='my_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='exchangeoffer',
            name='want_min_area',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='exchangeoffer',
            name='want_min_rooms',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='exchangeofferimage',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.exchangeoffer'),
        ),
        migrations.AlterField(
            model_name='marketlisting',
            name='living_area',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='marketlisting',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marketlisting',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='marketlisting',
            name='rooms',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='marketlistingimage',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.marketlisting'),
        ),
    ]
