# Generated by Django 5.1.12 on 2025-09-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_add_alt_text_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchangeoffer",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exchangeoffer",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketlisting",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketlisting",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
