# Generated by Django 5.1.11 on 2025-09-03 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_exchangeoffer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeoffer',
            name='my_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exchangeoffer',
            name='my_bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='exchangeoffer',
            name='my_floors',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='exchangeoffer',
            name='my_postcode',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='exchangeoffer',
            name='my_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='exchangeoffer',
            name='my_province',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='exchangeoffer',
            name='my_tenure',
            field=models.CharField(blank=True, choices=[('HUUR', 'Huur'), ('KOOP', 'Koop')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='exchangeoffer',
            name='new_build',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exchangeoffer',
            name='pets_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exchangeoffer',
            name='shed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exchangeoffer',
            name='wheelchair',
            field=models.BooleanField(default=False),
        ),
    ]
