# Generated by Django 5.1.11 on 2025-09-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_exchangeoffer_my_address_exchangeoffer_my_bedrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeoffer',
            name='my_cover',
            field=models.ImageField(blank=True, null=True, upload_to='exchange_covers/'),
        ),
    ]
