# Generated by Django 5.1.12 on 2025-09-07 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_add_lat_lng_fields"),
        ("properties", "0004_add_slug_to_exchangeoffer"),
    ]

    operations = []
