# Generated by Django 5.1.11 on 2025-09-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_exchangeoffer_my_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='tenure',
            field=models.CharField(blank=True, choices=[('HUUR', 'Huur'), ('KOOP', 'Koop')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='wish',
            name='want_balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='want_garage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='want_garden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='want_ground_floor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='want_lift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='want_near_ov',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='want_near_schools',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='want_near_shops',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='want_pets_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='want_shed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='want_storage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='want_terrace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='want_wheelchair',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wish',
            name='bedrooms',
            field=models.PositiveIntegerField(blank=True, help_text='Min. slaapkamers', null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='city',
            field=models.CharField(blank=True, help_text='Gewenste plaats(en) / regio, komma-gescheiden', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='features',
            field=models.TextField(blank=True, help_text='Extra wensen, komma-gescheiden', null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budget (max. huur/koop)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='rooms',
            field=models.PositiveIntegerField(blank=True, help_text='Min. kamers', null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='size',
            field=models.PositiveIntegerField(blank=True, help_text='Min. woonoppervlakte (m²)', null=True),
        ),
    ]
