# Generated by Django 5.1.11 on 2025-09-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_wish_tenure_wish_want_balcony_wish_want_garage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='tenure',
        ),
        migrations.AlterField(
            model_name='wish',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max. huurprijs (€)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='type',
            field=models.CharField(blank=True, choices=[('appartement', 'Appartement'), ('rijtjeshuis', 'Rijtjeshuis'), ('vrijstaand', 'Vrijstaand'), ('studio', 'Studio'), ('tussenwoning', 'Tussenwoning'), ('hoekwoning', 'Hoekwoning')], help_text='Type woning', max_length=20, null=True),
        ),
    ]
