# Generated by Django 5.1.11 on 2025-09-03 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_remove_wish_tenure_alter_wish_price_alter_wish_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangeoffer',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='exchangeoffer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='exchangeoffer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='marketlisting',
            name='attic',
        ),
        migrations.RemoveField(
            model_name='marketlisting',
            name='cellar',
        ),
        migrations.RemoveField(
            model_name='marketlisting',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='marketlisting',
            name='floorplan',
        ),
        migrations.RemoveField(
            model_name='marketlisting',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='marketlisting',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='marketlisting',
            name='near_schools',
        ),
        migrations.RemoveField(
            model_name='marketlisting',
            name='near_shops',
        ),
        migrations.RemoveField(
            model_name='marketlisting',
            name='ov',
        ),
        migrations.RemoveField(
            model_name='marketlisting',
            name='parking_private',
        ),
        migrations.RemoveField(
            model_name='marketlisting',
            name='parking_street',
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='build_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='energy_label',
            field=models.CharField(choices=[('A++++', 'A++++'), ('A+++', 'A+++'), ('A++', 'A++'), ('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('ONBEKEND', 'Onbekend')], default='ONBEKEND', max_length=10),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='finish',
            field=models.CharField(blank=True, choices=[('KAAL', 'Kaal'), ('GESTOFFEERD', 'Gestoffeerd'), ('GEMEUBILEERD', 'Gemeubileerd')], max_length=20),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='floors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='heat_pump',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='lot_area',
            field=models.PositiveIntegerField(blank=True, help_text='Perceel m²', null=True),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='new_build',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='parking_spot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='pets_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='postcode',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='province',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='rental_term',
            field=models.CharField(blank=True, choices=[('BEPAALDE_TIJD', 'Bepaalde tijd'), ('ONBEPAALDE_TIJD', 'Onbepaalde tijd')], max_length=20),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='roof_terrace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='service_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='shed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='smoking_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='solar_panels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='suitable_for',
            field=models.TextField(blank=True, help_text='CSV: studenten, gezin, expats'),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='wheelchair_accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exchangeoffer',
            name='my_property_type',
            field=models.CharField(blank=True, choices=[('appartement', 'Appartement'), ('eengezinswoning', 'Eengezinswoning'), ('rijtjeshuis', 'Rijtjeshuis'), ('vrijstaand', 'Vrijstaand'), ('studio', 'Studio'), ('tussenwoning', 'Tussenwoning'), ('hoekwoning', 'Hoekwoning'), ('villa', 'Villa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='exchangeoffer',
            name='want_property_type',
            field=models.CharField(blank=True, choices=[('appartement', 'Appartement'), ('eengezinswoning', 'Eengezinswoning'), ('rijtjeshuis', 'Rijtjeshuis'), ('vrijstaand', 'Vrijstaand'), ('studio', 'Studio'), ('tussenwoning', 'Tussenwoning'), ('hoekwoning', 'Hoekwoning'), ('villa', 'Villa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marketlisting',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='marketlisting',
            name='listing_kind',
            field=models.CharField(choices=[('HUUR', 'Huur'), ('KOOP', 'Koop')], default='KOOP', max_length=8),
        ),
        migrations.AlterField(
            model_name='marketlisting',
            name='living_area',
            field=models.PositiveIntegerField(help_text='m²', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='marketlisting',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='marketlisting',
            name='property_type',
            field=models.CharField(choices=[('appartement', 'Appartement'), ('eengezinswoning', 'Eengezinswoning'), ('rijtjeshuis', 'Rijtjeshuis'), ('vrijstaand', 'Vrijstaand'), ('studio', 'Studio'), ('tussenwoning', 'Tussenwoning'), ('hoekwoning', 'Hoekwoning'), ('villa', 'Villa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marketlisting',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='wish',
            name='bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='city',
            field=models.CharField(blank=True, help_text='Gewenste plaats(en), komma-gescheiden', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='rooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='type',
            field=models.CharField(blank=True, choices=[('appartement', 'Appartement'), ('eengezinswoning', 'Eengezinswoning'), ('rijtjeshuis', 'Rijtjeshuis'), ('vrijstaand', 'Vrijstaand'), ('studio', 'Studio'), ('tussenwoning', 'Tussenwoning'), ('hoekwoning', 'Hoekwoning'), ('villa', 'Villa')], max_length=20, null=True),
        ),
    ]
