# Generated by Django 5.1.11 on 2025-09-03 08:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_exchangeoffer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeoffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangeoffer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
