# Generated by Django 5.1.11 on 2025-09-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_exchangeoffer_created_at_exchangeoffer_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketlisting',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
